# Generated by Django 6.0.4 on 2026-05-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('employeeid', models.CharField(db_column='EmployeeID', max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, db_column='Passpin', max_length=255, null=True)),
                ('phonenumber', models.CharField(db_column='PhoneNumber', max_length=20)),
                ('firstname', models.CharField(db_column='FirstName', max_length=100)),
                ('lastname', models.CharField(db_column='LastName', max_length=100)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=255, null=True, unique=True)),
                ('is_temporary', models.BooleanField(db_column='is_temporary', default=True)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('lastlogin', models.DateTimeField(blank=True, db_column='LastLogin', null=True)),
                ('lastresetdate', models.DateTimeField(blank=True, db_column='LastResetDate', null=True)),
                ('profilepic', models.CharField(blank=True, db_column='ProfilePic', max_length=255, null=True)),
                ('microsoftid', models.CharField(blank=True, db_column='MicrosoftID', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accesslevel',
            fields=[
                ('accessid', models.AutoField(db_column='AccessID', primary_key=True, serialize=False)),
                ('accessrole', models.CharField(db_column='AccessRole', max_length=255)),
                ('accessdescription', models.CharField(blank=True, db_column='AccessDescription', max_length=500, null=True)),
            ],
            options={
                'db_table': 'AccessLevel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.AutoField(db_column='DepartmentID', primary_key=True, serialize=False)),
                ('departmentname', models.CharField(db_column='DepartmentName', max_length=255)),
                ('isactive', models.IntegerField(db_column='IsActive')),
            ],
            options={
                'db_table': 'Department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleid', models.AutoField(db_column='RoleID', primary_key=True, serialize=False)),
                ('rolename', models.CharField(db_column='RoleName', max_length=100)),
                ('isuniqueassignment', models.IntegerField(blank=True, db_column='IsUniqueAssignment', null=True)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
    ]
