# Generated by Django 5.2.14 on 2026-06-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hasaccess",
            field=models.BooleanField(db_column="HasAccess", default=True),
        ),
    ]
