# Generated by Django 5.2.14 on 2026-07-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_hasaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="roles",
            name="vacationhours",
            field=models.IntegerField(blank=True, db_column="VacationHours", null=True),
        ),
    ]
