# Generated by Django 5.2.14 on 2026-07-21 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_roles_vacationhours"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "positionid",
                    models.AutoField(
                        db_column="PositionID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "positionname",
                    models.CharField(db_column="PositionName", max_length=100),
                ),
                ("isactive", models.IntegerField(db_column="IsActive", default=1)),
            ],
            options={
                "db_table": "Position",
                "ordering": ["positionname"],
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="crewassignment",
            name="positionid",
            field=models.ForeignKey(
                blank=True,
                db_column="PositionID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.position",
            ),
        ),
    ]
