# Generated by Django 5.2.14 on 2026-08-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_add_crewcoverage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="shiftertype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Production", "Production"),
                    ("Development", "Development"),
                    ("Longhole", "Longhole"),
                    ("Logistics", "Logistics"),
                ],
                db_column="ShifterType",
                max_length=20,
                null=True,
            ),
        ),
    ]
