# Generated by Django 5.2.14 on 2026-08-17 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0027_statholiday_province_businessentry_dateworked"),
        ("users", "0006_add_shiftertype_and_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="crewid",
            field=models.ForeignKey(
                blank=True,
                db_column="CrewID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifters",
                to="timesheets.crews",
            ),
        ),
    ]
