# Generated by Django 5.2.14 on 2026-08-18 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0027_statholiday_province_businessentry_dateworked"),
        ("users", "0007_user_crewid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accountid",
            field=models.ForeignKey(
                blank=True,
                db_column="AccountID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="account_employees",
                to="timesheets.account",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="contractid",
            field=models.ForeignKey(
                blank=True,
                db_column="ContractID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_employees",
                to="timesheets.contract",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="employmenttype",
            field=models.CharField(
                choices=[("Staff", "Staff"), ("Contract", "Contract")],
                db_column="EmploymentType",
                default="Staff",
                max_length=10,
            ),
        ),
    ]
