# Generated by Django 5.2.14 on 2026-08-18 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_pk_swap"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrewAssignment",
            fields=[
                (
                    "assignmentid",
                    models.AutoField(
                        db_column="AssignmentID", primary_key=True, serialize=False
                    ),
                ),
                ("startdate", models.DateField(db_column="StartDate")),
                (
                    "enddate",
                    models.DateField(blank=True, db_column="EndDate", null=True),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="EmployeeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="crew_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "positionid",
                    models.ForeignKey(
                        blank=True,
                        db_column="PositionID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.position",
                    ),
                ),
                (
                    "shifter",
                    models.ForeignKey(
                        db_column="ShifterID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="crew_led",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "CrewAssignment",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CrewCoverage",
            fields=[
                (
                    "coverageid",
                    models.AutoField(
                        db_column="CoverageID", primary_key=True, serialize=False
                    ),
                ),
                ("startdate", models.DateField(db_column="StartDate")),
                (
                    "enddate",
                    models.DateField(blank=True, db_column="EndDate", null=True),
                ),
                ("notes", models.TextField(blank=True, db_column="Notes", null=True)),
                (
                    "assignedat",
                    models.DateTimeField(auto_now_add=True, db_column="AssignedAt"),
                ),
                (
                    "assignedby",
                    models.ForeignKey(
                        db_column="AssignedBy",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="coverages_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "covering_shifter",
                    models.ForeignKey(
                        db_column="CoveringShifterID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="coverages_covering",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "home_shifter",
                    models.ForeignKey(
                        db_column="HomeShifterID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="coverages_home",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "CrewCoverage",
                "ordering": ["-startdate"],
                "managed": True,
            },
        ),
    ]
