# Generated by Django 5.2.14 on 2026-09-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_crewassignment_crewcoverage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hiredate",
            field=models.DateField(blank=True, db_column="HireDate", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="terminationdate",
            field=models.DateField(blank=True, db_column="TerminationDate", null=True),
        ),
    ]
