# Generated by Django 5.2.14 on 2026-09-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_hiredate_user_terminationdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="roles",
            name="showsleavebalance",
            field=models.BooleanField(db_column="ShowsLeaveBalance", default=True),
        ),
    ]
