# Generated by Django 5.2.14 on 2026-09-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_roles_showsleavebalance"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="minerlevel",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Level 1"), (2, "Level 2")],
                db_column="MinerLevel",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="roles",
            name="showsleavebalance",
            field=models.BooleanField(db_column="ShowsLeaveBalance", default=False),
        ),
    ]
