# Generated by Django 5.2.14 on 2026-09-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_minerlevel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="minerlevel",
            field=models.CharField(
                blank=True,
                choices=[("L1", "L1"), ("L2", "L2")],
                db_column="MinerLevel",
                max_length=2,
                null=True,
            ),
        ),
    ]
