# Generated by Django 5.2.14 on 2026-09-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_user_minerlevel_as_L"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="minerlevel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Lead", "Lead"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                ],
                db_column="MinerLevel",
                max_length=4,
                null=True,
            ),
        ),
    ]
