# Generated by Django 5.2.14 on 2026-09-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_minerlevel_full_scale"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="shiftertype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Production", "Production"),
                    ("Development", "Development"),
                    ("Longhole", "Longhole"),
                    ("Logistics", "Logistics"),
                ],
                db_column="ShifterType",
                max_length=20,
                null=True,
            ),
        ),
    ]
