# Generated by Django 5.2.14 on 2026-09-14 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0034_seed_ispayable_defaults"),
        ("users", "0017_position_shiftertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="crewassignment",
            name="crewid",
            field=models.ForeignKey(
                blank=True,
                db_column="CrewID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="timesheets.crews",
            ),
        ),
        migrations.AddField(
            model_name="crewassignment",
            name="shiftertype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Production", "Production"),
                    ("Development", "Development"),
                    ("Longhole", "Longhole"),
                    ("Logistics", "Logistics"),
                ],
                db_column="ShifterType",
                max_length=20,
                null=True,
            ),
        ),
    ]
