# Generated by Django 5.2.14 on 2026-09-14 17:17

from django.db import migrations


def backfill_basket(apps, schema_editor):
    """Every CrewAssignment row created before this field existed implicitly
    trusted shifter.crewid/shiftertype as its basket. Stamp that same value
    onto each row now (best-effort for ended rows too, since no historical
    snapshot exists) so nothing is left blank going forward."""
    CrewAssignment = apps.get_model('users', 'CrewAssignment')
    for assignment in CrewAssignment.objects.select_related('shifter').filter(crewid__isnull=True, shiftertype__isnull=True):
        shifter = assignment.shifter
        if shifter.crewid_id or shifter.shiftertype:
            assignment.crewid_id = shifter.crewid_id
            assignment.shiftertype = shifter.shiftertype
            assignment.save(update_fields=['crewid', 'shiftertype'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_crewassignment_basket"),
    ]

    operations = [
        migrations.RunPython(backfill_basket, noop_reverse),
    ]
