# Generated by Django 5.2.14 on 2026-09-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_crewassignment_basket_backfill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="minerlevel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Staff", "Staff"),
                    ("Lead", "Lead"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                ],
                db_column="MinerLevel",
                max_length=6,
                null=True,
            ),
        ),
    ]
