# Generated by Django 5.2.14 on 2026-09-15 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_user_minerlevel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewassignment",
            name="shifter",
            field=models.ForeignKey(
                blank=True,
                db_column="ShifterID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="crew_led",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
