# Generated by Django 5.2.14 on 2026-09-15 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0035_minerlevel_contract_levels"),
        ("users", "0021_alter_crewassignment_shifter"),
    ]

    operations = [
        migrations.AddField(
            model_name="crewcoverage",
            name="crewid",
            field=models.ForeignKey(
                blank=True,
                db_column="CrewID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="timesheets.crews",
            ),
        ),
        migrations.AddField(
            model_name="crewcoverage",
            name="shiftertype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Production", "Production"),
                    ("Development", "Development"),
                    ("Longhole", "Longhole"),
                    ("Logistics", "Logistics"),
                ],
                db_column="ShifterType",
                max_length=20,
                null=True,
            ),
        ),
    ]
