# Generated by Django 5.2.14 on 2026-05-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auditlog",
            fields=[
                (
                    "logid",
                    models.AutoField(
                        db_column="LogID", primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(db_column="Action", max_length=50)),
                ("tablename", models.CharField(db_column="TableName", max_length=50)),
                ("recordid", models.IntegerField(db_column="RecordID")),
                (
                    "oldvalue",
                    models.JSONField(blank=True, db_column="OldValue", null=True),
                ),
                (
                    "newvalue",
                    models.JSONField(blank=True, db_column="NewValue", null=True),
                ),
                ("timestamp", models.DateTimeField(db_column="Timestamp")),
            ],
            options={
                "db_table": "AuditLog",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Crews",
            fields=[
                (
                    "crewid",
                    models.AutoField(
                        db_column="CrewID", primary_key=True, serialize=False
                    ),
                ),
                ("crewname", models.CharField(db_column="CrewName", max_length=10)),
                ("isactive", models.IntegerField(db_column="IsActive")),
            ],
            options={
                "db_table": "Crews",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Timesheetentry",
            fields=[
                (
                    "entryid",
                    models.AutoField(
                        db_column="EntryID", primary_key=True, serialize=False
                    ),
                ),
                ("shifttype", models.CharField(db_column="ShiftType", max_length=5)),
                (
                    "hoursworked",
                    models.DecimalField(
                        db_column="HoursWorked", decimal_places=2, max_digits=5
                    ),
                ),
                (
                    "entrydescription",
                    models.TextField(
                        blank=True, db_column="EntryDescription", null=True
                    ),
                ),
                ("startdate", models.DateField(db_column="StartDate")),
                (
                    "enddate",
                    models.DateField(blank=True, db_column="EndDate", null=True),
                ),
                ("linestatus", models.CharField(db_column="LineStatus", max_length=8)),
                (
                    "approvedat",
                    models.DateTimeField(blank=True, db_column="ApprovedAt", null=True),
                ),
                (
                    "supervisornote",
                    models.TextField(blank=True, db_column="SupervisorNote", null=True),
                ),
            ],
            options={
                "db_table": "TimesheetEntry",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Timesheetheader",
            fields=[
                (
                    "headerid",
                    models.AutoField(
                        db_column="HeaderID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "overallstatus",
                    models.CharField(db_column="OverallStatus", max_length=9),
                ),
                ("startedat", models.DateTimeField(db_column="StartedAt")),
                (
                    "submittedat",
                    models.DateTimeField(
                        blank=True, db_column="SubmittedAt", null=True
                    ),
                ),
            ],
            options={
                "db_table": "TimesheetHeader",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Workcategory",
            fields=[
                (
                    "categoryid",
                    models.AutoField(
                        db_column="CategoryID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "categoryname",
                    models.CharField(db_column="CategoryName", max_length=255),
                ),
                ("isproductive", models.IntegerField(db_column="IsProductive")),
                ("isactive", models.IntegerField(db_column="IsActive")),
            ],
            options={
                "db_table": "WorkCategory",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Workordercache",
            fields=[
                (
                    "workorderid",
                    models.CharField(
                        db_column="WorkOrderID",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="Description", max_length=255, null=True
                    ),
                ),
                (
                    "functionalgroup",
                    models.CharField(
                        blank=True,
                        db_column="FunctionalGroup",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("sap_startdate", models.DateField(db_column="SAP_StartDate")),
                (
                    "sap_completiondate",
                    models.DateField(
                        blank=True, db_column="SAP_CompletionDate", null=True
                    ),
                ),
            ],
            options={
                "db_table": "WorkOrderCache",
                "managed": True,
            },
        ),
    ]
