# Generated by Django 5.2.14 on 2026-05-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "accountid",
                    models.AutoField(
                        db_column="AccountID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "accountcode",
                    models.CharField(db_column="AccountCode", max_length=20),
                ),
                (
                    "accounttitle",
                    models.CharField(db_column="AccountTitle", max_length=255),
                ),
                (
                    "accountdescription",
                    models.TextField(
                        blank=True, db_column="AccountDescription", null=True
                    ),
                ),
                ("isactive", models.IntegerField(db_column="IsActive", default=1)),
            ],
            options={
                "db_table": "Account",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Auditlog",
            fields=[
                (
                    "logid",
                    models.AutoField(
                        db_column="LogID", primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(db_column="Action", max_length=50)),
                ("tablename", models.CharField(db_column="TableName", max_length=50)),
                ("recordid", models.IntegerField(db_column="RecordID")),
                (
                    "oldvalue",
                    models.JSONField(blank=True, db_column="OldValue", null=True),
                ),
                (
                    "newvalue",
                    models.JSONField(blank=True, db_column="NewValue", null=True),
                ),
                ("timestamp", models.DateTimeField(db_column="Timestamp")),
            ],
            options={
                "db_table": "AuditLog",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "contractid",
                    models.AutoField(
                        db_column="ContractID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "contractcode",
                    models.CharField(db_column="ContractCode", max_length=20),
                ),
                (
                    "contracttitle",
                    models.CharField(db_column="ContractTitle", max_length=255),
                ),
                (
                    "contractdescription",
                    models.TextField(
                        blank=True, db_column="ContractDescription", null=True
                    ),
                ),
                ("isactive", models.IntegerField(db_column="IsActive", default=1)),
            ],
            options={
                "db_table": "Contract",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Crews",
            fields=[
                (
                    "crewid",
                    models.AutoField(
                        db_column="CrewID", primary_key=True, serialize=False
                    ),
                ),
                ("crewname", models.CharField(db_column="CrewName", max_length=10)),
                ("isactive", models.IntegerField(db_column="IsActive", default=1)),
            ],
            options={
                "db_table": "Crews",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MaintenanceEntry",
            fields=[
                (
                    "mainentryid",
                    models.AutoField(
                        db_column="MainEntryID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "shifttype",
                    models.CharField(
                        choices=[("Day", "Day"), ("Night", "Night")],
                        db_column="ShiftType",
                        max_length=5,
                    ),
                ),
                (
                    "hoursworked",
                    models.DecimalField(
                        db_column="HoursWorked", decimal_places=2, max_digits=5
                    ),
                ),
                (
                    "entrydescription",
                    models.TextField(
                        blank=True, db_column="EntryDescription", null=True
                    ),
                ),
                ("startdate", models.DateField(db_column="StartDate")),
                (
                    "enddate",
                    models.DateField(blank=True, db_column="EndDate", null=True),
                ),
                (
                    "linestatus",
                    models.CharField(
                        db_column="LineStatus", default="Draft", max_length=15
                    ),
                ),
                (
                    "approvedat",
                    models.DateTimeField(blank=True, db_column="ApprovedAt", null=True),
                ),
                (
                    "supervisornote",
                    models.TextField(blank=True, db_column="SupervisorNote", null=True),
                ),
            ],
            options={
                "db_table": "MaintenanceEntry",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MaintenanceHeader",
            fields=[
                (
                    "mainheaderid",
                    models.AutoField(
                        db_column="MainHeaderID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "overallstatus",
                    models.CharField(
                        db_column="OverallStatus", default="Draft", max_length=25
                    ),
                ),
                (
                    "startedat",
                    models.DateTimeField(auto_now_add=True, db_column="StartedAt"),
                ),
                (
                    "submittedat",
                    models.DateTimeField(
                        blank=True, db_column="SubmittedAt", null=True
                    ),
                ),
            ],
            options={
                "db_table": "MaintenanceHeader",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="OperationsEntry",
            fields=[
                (
                    "opsentryid",
                    models.AutoField(
                        db_column="OpsEntryID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "hoursworked",
                    models.DecimalField(
                        db_column="HoursWorked", decimal_places=2, max_digits=5
                    ),
                ),
                (
                    "entrydescription",
                    models.TextField(
                        blank=True, db_column="EntryDescription", null=True
                    ),
                ),
                (
                    "linestatus",
                    models.CharField(
                        db_column="LineStatus", default="Draft", max_length=15
                    ),
                ),
                (
                    "approvedat",
                    models.DateTimeField(blank=True, db_column="ApprovedAt", null=True),
                ),
                (
                    "captainnote",
                    models.TextField(blank=True, db_column="CaptainNote", null=True),
                ),
                (
                    "superintendentnote",
                    models.TextField(
                        blank=True, db_column="SuperintendentNote", null=True
                    ),
                ),
            ],
            options={
                "db_table": "OperationsEntry",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="OperationsHeader",
            fields=[
                (
                    "opsheaderid",
                    models.AutoField(
                        db_column="OpsHeaderID", primary_key=True, serialize=False
                    ),
                ),
                ("shiftdate", models.DateField(db_column="ShiftDate")),
                (
                    "shifttype",
                    models.CharField(
                        choices=[("Day", "Day"), ("Night", "Night")],
                        db_column="ShiftType",
                        max_length=5,
                    ),
                ),
                (
                    "overallstatus",
                    models.CharField(
                        db_column="OverallStatus", default="Draft", max_length=25
                    ),
                ),
                (
                    "startedat",
                    models.DateTimeField(auto_now_add=True, db_column="StartedAt"),
                ),
                (
                    "submittedat",
                    models.DateTimeField(
                        blank=True, db_column="SubmittedAt", null=True
                    ),
                ),
            ],
            options={
                "db_table": "OperationsHeader",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Workcategory",
            fields=[
                (
                    "categoryid",
                    models.AutoField(
                        db_column="CategoryID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "categoryname",
                    models.CharField(db_column="CategoryName", max_length=255),
                ),
                ("isproductive", models.IntegerField(db_column="IsProductive")),
                ("isactive", models.IntegerField(db_column="IsActive", default=1)),
            ],
            options={
                "db_table": "WorkCategory",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Workordercache",
            fields=[
                (
                    "workorderid",
                    models.CharField(
                        db_column="WorkOrderID",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="Description", max_length=255, null=True
                    ),
                ),
                (
                    "functionalgroup",
                    models.CharField(
                        blank=True,
                        db_column="FunctionalGroup",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("sap_startdate", models.DateField(db_column="SAP_StartDate")),
                (
                    "sap_completiondate",
                    models.DateField(
                        blank=True, db_column="SAP_CompletionDate", null=True
                    ),
                ),
            ],
            options={
                "db_table": "WorkOrderCache",
                "managed": True,
            },
        ),
    ]
