# Generated by Django 5.2.14 on 2026-05-18 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("timesheets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="employeeid",
            field=models.ForeignKey(
                db_column="EmployeeID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maintenanceheader",
            name="crewid",
            field=models.ForeignKey(
                blank=True,
                db_column="CrewID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.crews",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceheader",
            name="employeeid",
            field=models.ForeignKey(
                db_column="EmployeeID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maintenanceentry",
            name="mainheaderid",
            field=models.ForeignKey(
                db_column="MainHeaderID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.maintenanceheader",
            ),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="accountid",
            field=models.ForeignKey(
                db_column="AccountID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.account",
            ),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="contractid",
            field=models.ForeignKey(
                db_column="ContractID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.contract",
            ),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="employeeid",
            field=models.ForeignKey(
                db_column="EmployeeID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operationsheader",
            name="shifterid",
            field=models.ForeignKey(
                db_column="ShifterID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="opsheaderid",
            field=models.ForeignKey(
                db_column="OpsHeaderID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.operationsheader",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceentry",
            name="workcategoryid",
            field=models.ForeignKey(
                db_column="WorkCategoryID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.workcategory",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceentry",
            name="workorderid",
            field=models.ForeignKey(
                blank=True,
                db_column="WorkOrderID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.workordercache",
            ),
        ),
    ]
