# Generated by Django 5.2.14 on 2026-05-17 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("timesheets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="employeeid",
            field=models.ForeignKey(
                db_column="EmployeeID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timesheetheader",
            name="crewid",
            field=models.ForeignKey(
                blank=True,
                db_column="CrewID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.crews",
            ),
        ),
        migrations.AddField(
            model_name="timesheetheader",
            name="employeeid",
            field=models.ForeignKey(
                db_column="EmployeeID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="headerid",
            field=models.ForeignKey(
                db_column="HeaderID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.timesheetheader",
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="workcategoryid",
            field=models.ForeignKey(
                db_column="WorkCategoryID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.workcategory",
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="workorderid",
            field=models.ForeignKey(
                blank=True,
                db_column="WorkOrderID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.workordercache",
            ),
        ),
    ]
