# Generated by Django 5.2.14 on 2026-05-23 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="operationsentry",
            name="approvedby",
            field=models.ForeignKey(
                blank=True,
                db_column="ApprovedBy",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="approved_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameModel(
            old_name="MaintenanceHeader",
            new_name="MainHeader",
        ),
        migrations.AlterModelTable(
            name="mainheader",
            table="MainHeader",
        ),
        migrations.CreateModel(
            name="MainEntry",
            fields=[
                (
                    "mainentryid",
                    models.AutoField(
                        db_column="MainEntryID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "shifttype",
                    models.CharField(
                        choices=[("Day", "Day"), ("Night", "Night")],
                        db_column="ShiftType",
                        max_length=5,
                    ),
                ),
                (
                    "hoursworked",
                    models.DecimalField(
                        db_column="HoursWorked", decimal_places=2, max_digits=5
                    ),
                ),
                (
                    "entrydescription",
                    models.TextField(
                        blank=True, db_column="EntryDescription", null=True
                    ),
                ),
                ("startdate", models.DateField(db_column="StartDate")),
                (
                    "enddate",
                    models.DateField(blank=True, db_column="EndDate", null=True),
                ),
                (
                    "linestatus",
                    models.CharField(
                        db_column="LineStatus", default="Draft", max_length=15
                    ),
                ),
                (
                    "approvedat",
                    models.DateTimeField(blank=True, db_column="ApprovedAt", null=True),
                ),
                (
                    "supervisornote",
                    models.TextField(blank=True, db_column="SupervisorNote", null=True),
                ),
                (
                    "approvedby",
                    models.ForeignKey(
                        blank=True,
                        db_column="ApprovedBy",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="approved_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mainheaderid",
                    models.ForeignKey(
                        db_column="MainHeaderID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.mainheader",
                    ),
                ),
                (
                    "workcategoryid",
                    models.ForeignKey(
                        db_column="WorkCategoryID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.workcategory",
                    ),
                ),
                (
                    "workorderid",
                    models.ForeignKey(
                        blank=True,
                        db_column="WorkOrderID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.workordercache",
                    ),
                ),
            ],
            options={
                "db_table": "MainEntry",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="MaintenanceEntry",
        ),
    ]
