# Generated by Django 5.2.14 on 2026-05-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "timesheets",
            "0003_operationsentry_approvedby_alter_mainheader_table_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mainentry",
            name="sapworkid",
            field=models.CharField(
                blank=True, db_column="SAPWorkID", max_length=100, null=True
            ),
        ),
    ]
