# Generated by Django 5.2.14 on 2026-05-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0004_mainentry_sapworkid_workordercache_sap_workorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="workordercache",
            name="sap_workorder",
            field=models.CharField(
                blank=True, db_column="SAP_WorkOrder", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="workordercache",
            name="workorderid",
            field=models.AutoField(
                db_column="WorkOrderID", primary_key=True, serialize=False
            ),
        ),
    ]
