# Generated by Django 5.2.14 on 2026-05-26 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0005_workordercache_sap_workorder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainentry",
            name="mainheaderid",
            field=models.ForeignKey(
                db_column="MainHeaderID",
                on_delete=django.db.models.deletion.CASCADE,
                to="timesheets.mainheader",
            ),
        ),
    ]
