# Generated by Django 5.2.14 on 2026-06-13 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0006_alter_mainentry_mainheaderid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationsentry",
            name="approvedat",
        ),
        migrations.RemoveField(
            model_name="operationsentry",
            name="approvedby",
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="approvedat_capt",
            field=models.DateTimeField(
                blank=True, db_column="ApprovedAt_Capt", null=True
            ),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="approvedat_sup",
            field=models.DateTimeField(
                blank=True, db_column="ApprovedAt_Sup", null=True
            ),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="approvedby_capt",
            field=models.ForeignKey(
                blank=True,
                db_column="ApprovedBy_Capt",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="captain_approved_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="approvedby_sup",
            field=models.ForeignKey(
                blank=True,
                db_column="ApprovedBy_Sup",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="supervisor_approved_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
