# Generated by Django 5.2.14 on 2026-06-14 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0007_remove_operationsentry_approvedat_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mainheader",
            name="completedat",
            field=models.DateTimeField(blank=True, db_column="CompletedAt", null=True),
        ),
        migrations.AddField(
            model_name="operationsheader",
            name="ohapprovedat_capt",
            field=models.DateTimeField(
                blank=True, db_column="OHApprovedAt_Capt", null=True
            ),
        ),
        migrations.AddField(
            model_name="operationsheader",
            name="ohapprovedat_sup",
            field=models.DateTimeField(
                blank=True, db_column="OHApprovedAt_Sup", null=True
            ),
        ),
        migrations.AddField(
            model_name="operationsheader",
            name="ohapprovedby_capt",
            field=models.ForeignKey(
                blank=True,
                db_column="OpsHApprovedBy_Capt",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="captain_headerapproved_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operationsheader",
            name="ohapprovedby_sup",
            field=models.ForeignKey(
                blank=True,
                db_column="OpsHApprovedBy_Sup",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="supervisor_headerapproved_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
