# Generated by Django 5.2.14 on 2026-07-08 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0008_mainheader_completedat_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Businesscategory",
            fields=[
                (
                    "businesscategoryid",
                    models.AutoField(
                        db_column="CategoryID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "categoryname",
                    models.CharField(db_column="CategoryName", max_length=255),
                ),
                ("isproductive", models.IntegerField(db_column="IsProductive")),
                ("isactive", models.IntegerField(db_column="IsActive", default=1)),
            ],
            options={
                "db_table": "BusinessCategory",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BusinessHeader",
            fields=[
                (
                    "businessheaderid",
                    models.AutoField(
                        db_column="BusinessHeaderID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "periodmonth",
                    models.IntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        db_column="PeriodMonth",
                    ),
                ),
                ("periodyear", models.IntegerField(db_column="PeriodYear")),
                (
                    "overallstatus",
                    models.CharField(
                        db_column="OverallStatus", default="Draft", max_length=25
                    ),
                ),
                (
                    "startedat",
                    models.DateTimeField(auto_now_add=True, db_column="StartedAt"),
                ),
                (
                    "submittedat",
                    models.DateTimeField(
                        blank=True, db_column="SubmittedAt", null=True
                    ),
                ),
                (
                    "completedat",
                    models.DateTimeField(
                        blank=True, db_column="CompletedAt", null=True
                    ),
                ),
                (
                    "crewid",
                    models.ForeignKey(
                        blank=True,
                        db_column="CrewID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.crews",
                    ),
                ),
                (
                    "employeeid",
                    models.ForeignKey(
                        db_column="EmployeeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "BusinessHeader",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BusinessEntry",
            fields=[
                (
                    "businessentryid",
                    models.AutoField(
                        db_column="BusinessEntryID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "shifttype",
                    models.CharField(
                        blank=True,
                        choices=[("Day", "Day"), ("Night", "Night")],
                        db_column="ShiftType",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "hoursworked",
                    models.DecimalField(
                        db_column="HoursWorked", decimal_places=2, max_digits=5
                    ),
                ),
                (
                    "entrydescription",
                    models.TextField(
                        blank=True, db_column="EntryDescription", null=True
                    ),
                ),
                ("entrydate", models.DateField(db_column="EntryDate")),
                (
                    "linestatus",
                    models.CharField(
                        db_column="LineStatus", default="Draft", max_length=15
                    ),
                ),
                (
                    "approvedat",
                    models.DateTimeField(blank=True, db_column="ApprovedAt", null=True),
                ),
                (
                    "supervisornote",
                    models.TextField(blank=True, db_column="SupervisorNote", null=True),
                ),
                (
                    "approvedby",
                    models.ForeignKey(
                        blank=True,
                        db_column="ApprovedBy",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="approved_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "businesscategoryid",
                    models.ForeignKey(
                        db_column="BusinessCategoryID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.businesscategory",
                    ),
                ),
                (
                    "businessheaderid",
                    models.ForeignKey(
                        db_column="BusinessHeaderID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timesheets.businessheader",
                    ),
                ),
            ],
            options={
                "db_table": "BusinessEntry",
                "managed": True,
            },
        ),
    ]
