# Generated by Django 5.2.14 on 2026-07-09 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0009_businesscategory_businessheader_businessentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="businessheader",
            name="paidat",
            field=models.DateTimeField(blank=True, db_column="PaidAt", null=True),
        ),
        migrations.AddField(
            model_name="businessheader",
            name="paidby",
            field=models.ForeignKey(
                blank=True,
                db_column="PaidBy",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="paid_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mainheader",
            name="paidat",
            field=models.DateTimeField(blank=True, db_column="PaidAt", null=True),
        ),
        migrations.AddField(
            model_name="mainheader",
            name="paidby",
            field=models.ForeignKey(
                blank=True,
                db_column="PaidBy",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="paid_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operationsheader",
            name="paidat",
            field=models.DateTimeField(blank=True, db_column="PaidAt", null=True),
        ),
        migrations.AddField(
            model_name="operationsheader",
            name="paidby",
            field=models.ForeignKey(
                blank=True,
                db_column="PaidBy",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="paid_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
