# Generated by Django 5.2.14 on 2026-07-10 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0010_businessheader_paidat_businessheader_paidby_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "leavetypeid",
                    models.AutoField(
                        db_column="LeaveTypeID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "leavetypename",
                    models.CharField(db_column="LeaveTypeName", max_length=255),
                ),
                ("isactive", models.IntegerField(db_column="IsActive", default=1)),
            ],
            options={
                "db_table": "LeaveType",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StatHoliday",
            fields=[
                (
                    "statid",
                    models.AutoField(
                        db_column="StatID", primary_key=True, serialize=False
                    ),
                ),
                ("statname", models.CharField(db_column="StatName", max_length=255)),
                ("statdate", models.DateField(db_column="StatDate")),
                ("isactive", models.IntegerField(db_column="IsActive", default=1)),
            ],
            options={
                "db_table": "StatHoliday",
                "managed": True,
            },
        ),
        migrations.AlterField(
            model_name="businessentry",
            name="businesscategoryid",
            field=models.ForeignKey(
                blank=True,
                db_column="BusinessCategoryID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.businesscategory",
            ),
        ),
        migrations.AlterField(
            model_name="mainentry",
            name="workcategoryid",
            field=models.ForeignKey(
                blank=True,
                db_column="WorkCategoryID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.workcategory",
            ),
        ),
        migrations.CreateModel(
            name="LeaveAllocation",
            fields=[
                (
                    "allocationid",
                    models.AutoField(
                        db_column="AllocationID", primary_key=True, serialize=False
                    ),
                ),
                ("year", models.IntegerField(db_column="Year")),
                (
                    "allocatedhours",
                    models.DecimalField(
                        db_column="AllocatedHours", decimal_places=2, max_digits=5
                    ),
                ),
                ("isprorated", models.IntegerField(db_column="IsProrated", default=0)),
                (
                    "employeeid",
                    models.ForeignKey(
                        db_column="EmployeeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leavetypeid",
                    models.ForeignKey(
                        db_column="LeaveTypeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.leavetype",
                    ),
                ),
            ],
            options={
                "db_table": "LeaveAllocation",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="businessentry",
            name="leavetypeid",
            field=models.ForeignKey(
                blank=True,
                db_column="LeaveTypeID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.leavetype",
            ),
        ),
        migrations.AddField(
            model_name="mainentry",
            name="leavetypeid",
            field=models.ForeignKey(
                blank=True,
                db_column="LeaveTypeID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.leavetype",
            ),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="leavetypeid",
            field=models.ForeignKey(
                blank=True,
                db_column="LeaveTypeID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.leavetype",
            ),
        ),
    ]
