# Generated by Django 5.2.14 on 2026-07-10 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0011_leavetype_statholiday_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationsheader",
            name="paidat",
        ),
        migrations.RemoveField(
            model_name="operationsheader",
            name="paidby",
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="paidat",
            field=models.DateTimeField(blank=True, db_column="PaidAt", null=True),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="paidby",
            field=models.ForeignKey(
                blank=True,
                db_column="PaidBy",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="paid_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
