# Generated by Django 5.2.14 on 2026-07-19 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0012_remove_operationsheader_paidat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationsentry",
            name="entrydescription",
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="hauledto",
            field=models.CharField(
                blank=True, db_column="HauledTo", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="longholefootage",
            field=models.DecimalField(
                blank=True,
                db_column="LongHoleFootage",
                decimal_places=2,
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="lowgradehauled",
            field=models.DecimalField(
                blank=True,
                db_column="LowGradeHauled",
                decimal_places=2,
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="lowgradeskipped",
            field=models.DecimalField(
                blank=True,
                db_column="LowGradeSkipped",
                decimal_places=2,
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="remarks",
            field=models.TextField(blank=True, db_column="Remarks", null=True),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="tonnesorehouled",
            field=models.DecimalField(
                blank=True,
                db_column="TonnesOreHauled",
                decimal_places=2,
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="tonnesoreskipped",
            field=models.DecimalField(
                blank=True,
                db_column="TonnesOreSkipped",
                decimal_places=2,
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="tonneswastehauled",
            field=models.DecimalField(
                blank=True,
                db_column="TonnesWasteHauled",
                decimal_places=2,
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="tonneswasteskipped",
            field=models.DecimalField(
                blank=True,
                db_column="TonnesWasteSkipped",
                decimal_places=2,
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="operationsheader",
            name="crewid",
            field=models.ForeignKey(
                blank=True,
                db_column="CrewID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.crews",
            ),
        ),
    ]
