# Generated by Django 5.2.14 on 2026-07-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0013_remove_operationsentry_entrydescription_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operationsentry",
            old_name="tonnesorehouled",
            new_name="tonnesorehauled",
        ),
    ]
