# Generated by Django 5.2.14 on 2026-07-19 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0014_rename_tonnesorehouled_operationsentry_tonnesorehauled"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationsentry",
            name="Workcategory",
            field=models.ForeignKey(
                blank=True,
                db_column="WorkCategoryID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.workcategory",
            ),
        ),
    ]
