# Generated by Django 5.2.14 on 2026-07-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0015_operationsentry_workcategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operationsentry",
            old_name="Workcategory",
            new_name="workcategory",
        ),
    ]
