# Generated by Django 5.2.14 on 2026-07-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0016_rename_workcategory_operationsentry_workcategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operationsentry",
            old_name="workcategory",
            new_name="workcategoryid",
        ),
    ]
