# Generated by Django 5.2.14 on 2026-07-19 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0017_rename_workcategory_operationsentry_workcategoryid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationsheader",
            name="crewid",
            field=models.ForeignKey(
                db_column="CrewID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.crews",
            ),
        ),
    ]
