# Generated by Django 5.2.14 on 2026-07-20 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0018_alter_operationsheader_crewid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationsentry",
            name="approvedat_sup",
        ),
        migrations.RemoveField(
            model_name="operationsentry",
            name="approvedby_sup",
        ),
        migrations.RemoveField(
            model_name="operationsentry",
            name="leavetypeid",
        ),
        migrations.RemoveField(
            model_name="operationsentry",
            name="superintendentnote",
        ),
        migrations.RemoveField(
            model_name="operationsheader",
            name="ohapprovedat_sup",
        ),
        migrations.RemoveField(
            model_name="operationsheader",
            name="ohapprovedby_sup",
        ),
        migrations.AlterField(
            model_name="operationsentry",
            name="accountid",
            field=models.ForeignKey(
                blank=True,
                db_column="AccountID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.account",
            ),
        ),
        migrations.CreateModel(
            name="OperationsBonus",
            fields=[
                (
                    "opsbonusid",
                    models.AutoField(
                        db_column="OpsBonusID", primary_key=True, serialize=False
                    ),
                ),
                ("bonusmonth", models.DateField(db_column="BonusMonth")),
                (
                    "bonusratecode",
                    models.CharField(
                        choices=[
                            ("1x", "1x"),
                            ("2x", "2x"),
                            ("3x", "3x"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                        ],
                        db_column="BonusRateCode",
                        max_length=2,
                    ),
                ),
                ("notes", models.TextField(blank=True, db_column="Notes", null=True)),
                (
                    "reviewedat",
                    models.DateTimeField(blank=True, db_column="ReviewedAt", null=True),
                ),
                (
                    "appliedatpayroll",
                    models.DateTimeField(
                        blank=True, db_column="AppliedAtPayroll", null=True
                    ),
                ),
                (
                    "appliedbypayroll",
                    models.ForeignKey(
                        blank=True,
                        db_column="AppliedByPayroll",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="applied_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employeeid",
                    models.ForeignKey(
                        db_column="EmployeeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewedby",
                    models.ForeignKey(
                        blank=True,
                        db_column="ReviewedBy",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reviewed_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "OperationsBonus",
                "managed": True,
                "unique_together": {("employeeid", "bonusmonth")},
            },
        ),
    ]
