# Generated by Django 5.2.14 on 2026-07-21 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0019_remove_operationsentry_approvedat_sup_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractAccount",
            fields=[
                (
                    "contractaccountid",
                    models.AutoField(
                        db_column="ContractAccountID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "accountid",
                    models.ForeignKey(
                        db_column="AccountID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timesheets.account",
                    ),
                ),
                (
                    "contractid",
                    models.ForeignKey(
                        db_column="ContractID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timesheets.contract",
                    ),
                ),
            ],
            options={
                "db_table": "ContractAccount",
                "managed": True,
                "unique_together": {("contractid", "accountid")},
            },
        ),
    ]
