# Generated by Django 5.2.14 on 2026-07-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0020_add_contractaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractSeries",
            fields=[
                (
                    "seriesid",
                    models.AutoField(
                        db_column="SeriesID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "seriesname",
                    models.CharField(db_column="SeriesName", max_length=100),
                ),
                ("sortorder", models.IntegerField(db_column="SortOrder", default=0)),
            ],
            options={
                "db_table": "ContractSeries",
                "ordering": ["sortorder", "seriesname"],
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="seriesid",
            field=models.ForeignKey(
                blank=True,
                db_column="SeriesID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="timesheets.contractseries",
            ),
        ),
    ]
