# Generated by Django 5.2.14 on 2026-07-21 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0021_add_contractseries"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeBonus",
            fields=[
                (
                    "employeebonusid",
                    models.AutoField(
                        db_column="EmployeeBonusID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "bonustype",
                    models.CharField(
                        choices=[("Year-End", "Year-End"), ("Ad-Hoc", "Ad-Hoc")],
                        db_column="BonusType",
                        max_length=10,
                    ),
                ),
                ("periodstart", models.DateField(db_column="PeriodStart")),
                ("periodend", models.DateField(db_column="PeriodEnd")),
                (
                    "bonusratecode",
                    models.CharField(
                        choices=[
                            ("1x", "1x"),
                            ("2x", "2x"),
                            ("3x", "3x"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                        ],
                        db_column="BonusRateCode",
                        max_length=2,
                    ),
                ),
                ("notes", models.TextField(blank=True, db_column="Notes", null=True)),
                (
                    "assignedat",
                    models.DateTimeField(auto_now_add=True, db_column="AssignedAt"),
                ),
                (
                    "appliedatpayroll",
                    models.DateTimeField(
                        blank=True, db_column="AppliedAtPayroll", null=True
                    ),
                ),
                (
                    "appliedbypayroll",
                    models.ForeignKey(
                        blank=True,
                        db_column="AppliedByPayroll",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="applied_employee_bonuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignedby",
                    models.ForeignKey(
                        db_column="AssignedBy",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="assigned_bonuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employeeid",
                    models.ForeignKey(
                        db_column="EmployeeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="bonuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "EmployeeBonus",
                "ordering": ["-periodend"],
                "managed": True,
            },
        ),
    ]
