# Generated by Django 5.2.14 on 2026-07-21 17:07

from django.db import migrations, models


def copy_series_fk_to_m2m(apps, schema_editor):
    Contract = apps.get_model('timesheets', 'Contract')
    for contract in Contract.objects.filter(seriesid__isnull=False):
        contract.series.add(contract.seriesid)


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0022_add_employeebonus"),
    ]

    operations = [
        # 1. Create the M2M junction table first
        migrations.AddField(
            model_name="contract",
            name="series",
            field=models.ManyToManyField(
                blank=True,
                db_table="ContractSeriesMap",
                related_name="contracts",
                to="timesheets.contractseries",
            ),
        ),
        # 2. Copy existing FK assignments into the junction table
        migrations.RunPython(copy_series_fk_to_m2m, migrations.RunPython.noop),
        # 3. Now safe to drop the old FK column
        migrations.RemoveField(
            model_name="contract",
            name="seriesid",
        ),
    ]
