# Generated by Django 5.2.14 on 2026-08-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0025_operationsbonus_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationsheader",
            name="section",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Production", "Production"),
                    ("Development", "Development"),
                    ("Longhole", "Longhole"),
                    ("Logistics", "Logistics"),
                ],
                db_column="Section",
                max_length=20,
                null=True,
            ),
        ),
    ]
