# Generated by Django 5.2.14 on 2026-08-18 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0028_drop_employee_referencing_tables"),
        ("users", "0011_crewassignment_crewcoverage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Auditlog",
            fields=[
                (
                    "logid",
                    models.AutoField(
                        db_column="LogID", primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(db_column="Action", max_length=50)),
                ("tablename", models.CharField(db_column="TableName", max_length=50)),
                ("recordid", models.IntegerField(db_column="RecordID")),
                (
                    "oldvalue",
                    models.JSONField(blank=True, db_column="OldValue", null=True),
                ),
                (
                    "newvalue",
                    models.JSONField(blank=True, db_column="NewValue", null=True),
                ),
                ("timestamp", models.DateTimeField(db_column="Timestamp")),
                (
                    "employeeid",
                    models.ForeignKey(
                        db_column="EmployeeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "AuditLog",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BusinessHeader",
            fields=[
                (
                    "businessheaderid",
                    models.AutoField(
                        db_column="BusinessHeaderID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "periodmonth",
                    models.IntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        db_column="PeriodMonth",
                    ),
                ),
                ("periodyear", models.IntegerField(db_column="PeriodYear")),
                (
                    "overallstatus",
                    models.CharField(
                        db_column="OverallStatus", default="Draft", max_length=25
                    ),
                ),
                (
                    "startedat",
                    models.DateTimeField(auto_now_add=True, db_column="StartedAt"),
                ),
                (
                    "submittedat",
                    models.DateTimeField(
                        blank=True, db_column="SubmittedAt", null=True
                    ),
                ),
                (
                    "completedat",
                    models.DateTimeField(
                        blank=True, db_column="CompletedAt", null=True
                    ),
                ),
                (
                    "paidat",
                    models.DateTimeField(blank=True, db_column="PaidAt", null=True),
                ),
                (
                    "crewid",
                    models.ForeignKey(
                        blank=True,
                        db_column="CrewID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.crews",
                    ),
                ),
                (
                    "employeeid",
                    models.ForeignKey(
                        db_column="EmployeeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paidby",
                    models.ForeignKey(
                        blank=True,
                        db_column="PaidBy",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="paid_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "BusinessHeader",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BusinessEntry",
            fields=[
                (
                    "businessentryid",
                    models.AutoField(
                        db_column="BusinessEntryID", primary_key=True, serialize=False
                    ),
                ),
                ("dateworked", models.DateField(db_column="DateWorked")),
                (
                    "shifttype",
                    models.CharField(
                        blank=True,
                        choices=[("Day", "Day"), ("Night", "Night")],
                        db_column="ShiftType",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "hoursworked",
                    models.DecimalField(
                        db_column="HoursWorked", decimal_places=2, max_digits=5
                    ),
                ),
                (
                    "entrydescription",
                    models.TextField(
                        blank=True, db_column="EntryDescription", null=True
                    ),
                ),
                (
                    "linestatus",
                    models.CharField(
                        db_column="LineStatus", default="Draft", max_length=15
                    ),
                ),
                (
                    "approvedat",
                    models.DateTimeField(blank=True, db_column="ApprovedAt", null=True),
                ),
                (
                    "supervisornote",
                    models.TextField(blank=True, db_column="SupervisorNote", null=True),
                ),
                (
                    "approvedby",
                    models.ForeignKey(
                        blank=True,
                        db_column="ApprovedBy",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="approved_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "businesscategoryid",
                    models.ForeignKey(
                        blank=True,
                        db_column="BusinessCategoryID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.businesscategory",
                    ),
                ),
                (
                    "leavetypeid",
                    models.ForeignKey(
                        blank=True,
                        db_column="LeaveTypeID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.leavetype",
                    ),
                ),
                (
                    "businessheaderid",
                    models.ForeignKey(
                        db_column="BusinessHeaderID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timesheets.businessheader",
                    ),
                ),
            ],
            options={
                "db_table": "BusinessEntry",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="EmployeeBonus",
            fields=[
                (
                    "employeebonusid",
                    models.AutoField(
                        db_column="EmployeeBonusID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "bonustype",
                    models.CharField(
                        choices=[("Year-End", "Year-End"), ("Ad-Hoc", "Ad-Hoc")],
                        db_column="BonusType",
                        max_length=10,
                    ),
                ),
                ("periodstart", models.DateField(db_column="PeriodStart")),
                ("periodend", models.DateField(db_column="PeriodEnd")),
                (
                    "bonusratecode",
                    models.CharField(
                        choices=[
                            ("1x", "1x"),
                            ("2x", "2x"),
                            ("3x", "3x"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                        ],
                        db_column="BonusRateCode",
                        max_length=2,
                    ),
                ),
                ("notes", models.TextField(blank=True, db_column="Notes", null=True)),
                (
                    "assignedat",
                    models.DateTimeField(auto_now_add=True, db_column="AssignedAt"),
                ),
                (
                    "appliedatpayroll",
                    models.DateTimeField(
                        blank=True, db_column="AppliedAtPayroll", null=True
                    ),
                ),
                (
                    "appliedbypayroll",
                    models.ForeignKey(
                        blank=True,
                        db_column="AppliedByPayroll",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="applied_employee_bonuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignedby",
                    models.ForeignKey(
                        db_column="AssignedBy",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="assigned_bonuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employeeid",
                    models.ForeignKey(
                        db_column="EmployeeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="bonuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "EmployeeBonus",
                "ordering": ["-periodend"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LeaveAllocation",
            fields=[
                (
                    "allocationid",
                    models.AutoField(
                        db_column="AllocationID", primary_key=True, serialize=False
                    ),
                ),
                ("year", models.IntegerField(db_column="Year")),
                (
                    "allocatedhours",
                    models.DecimalField(
                        db_column="AllocatedHours", decimal_places=2, max_digits=5
                    ),
                ),
                ("isprorated", models.IntegerField(db_column="IsProrated", default=0)),
                (
                    "employeeid",
                    models.ForeignKey(
                        db_column="EmployeeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leavetypeid",
                    models.ForeignKey(
                        db_column="LeaveTypeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.leavetype",
                    ),
                ),
            ],
            options={
                "db_table": "LeaveAllocation",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MainHeader",
            fields=[
                (
                    "mainheaderid",
                    models.AutoField(
                        db_column="MainHeaderID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "overallstatus",
                    models.CharField(
                        db_column="OverallStatus", default="Draft", max_length=25
                    ),
                ),
                (
                    "startedat",
                    models.DateTimeField(auto_now_add=True, db_column="StartedAt"),
                ),
                (
                    "submittedat",
                    models.DateTimeField(
                        blank=True, db_column="SubmittedAt", null=True
                    ),
                ),
                (
                    "completedat",
                    models.DateTimeField(
                        blank=True, db_column="CompletedAt", null=True
                    ),
                ),
                (
                    "paidat",
                    models.DateTimeField(blank=True, db_column="PaidAt", null=True),
                ),
                (
                    "crewid",
                    models.ForeignKey(
                        blank=True,
                        db_column="CrewID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.crews",
                    ),
                ),
                (
                    "employeeid",
                    models.ForeignKey(
                        db_column="EmployeeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paidby",
                    models.ForeignKey(
                        blank=True,
                        db_column="PaidBy",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="paid_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "MainHeader",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MainEntry",
            fields=[
                (
                    "mainentryid",
                    models.AutoField(
                        db_column="MainEntryID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "sapworkid",
                    models.CharField(
                        blank=True, db_column="SAPWorkID", max_length=100, null=True
                    ),
                ),
                (
                    "shifttype",
                    models.CharField(
                        choices=[("Day", "Day"), ("Night", "Night")],
                        db_column="ShiftType",
                        max_length=5,
                    ),
                ),
                (
                    "hoursworked",
                    models.DecimalField(
                        db_column="HoursWorked", decimal_places=2, max_digits=5
                    ),
                ),
                (
                    "entrydescription",
                    models.TextField(
                        blank=True, db_column="EntryDescription", null=True
                    ),
                ),
                ("startdate", models.DateField(db_column="StartDate")),
                (
                    "enddate",
                    models.DateField(blank=True, db_column="EndDate", null=True),
                ),
                (
                    "linestatus",
                    models.CharField(
                        db_column="LineStatus", default="Draft", max_length=15
                    ),
                ),
                (
                    "approvedat",
                    models.DateTimeField(blank=True, db_column="ApprovedAt", null=True),
                ),
                (
                    "supervisornote",
                    models.TextField(blank=True, db_column="SupervisorNote", null=True),
                ),
                (
                    "approvedby",
                    models.ForeignKey(
                        blank=True,
                        db_column="ApprovedBy",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="approved_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leavetypeid",
                    models.ForeignKey(
                        blank=True,
                        db_column="LeaveTypeID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.leavetype",
                    ),
                ),
                (
                    "workcategoryid",
                    models.ForeignKey(
                        blank=True,
                        db_column="WorkCategoryID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.workcategory",
                    ),
                ),
                (
                    "workorderid",
                    models.ForeignKey(
                        blank=True,
                        db_column="WorkOrderID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.workordercache",
                    ),
                ),
                (
                    "mainheaderid",
                    models.ForeignKey(
                        db_column="MainHeaderID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timesheets.mainheader",
                    ),
                ),
            ],
            options={
                "db_table": "MainEntry",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="OperationsHeader",
            fields=[
                (
                    "opsheaderid",
                    models.AutoField(
                        db_column="OpsHeaderID", primary_key=True, serialize=False
                    ),
                ),
                ("shiftdate", models.DateField(db_column="ShiftDate")),
                (
                    "shifttype",
                    models.CharField(
                        choices=[("Day", "Day"), ("Night", "Night")],
                        db_column="ShiftType",
                        max_length=5,
                    ),
                ),
                (
                    "overallstatus",
                    models.CharField(
                        db_column="OverallStatus", default="Draft", max_length=25
                    ),
                ),
                (
                    "startedat",
                    models.DateTimeField(auto_now_add=True, db_column="StartedAt"),
                ),
                (
                    "submittedat",
                    models.DateTimeField(
                        blank=True, db_column="SubmittedAt", null=True
                    ),
                ),
                (
                    "ohapprovedat_capt",
                    models.DateTimeField(
                        blank=True, db_column="OHApprovedAt_Capt", null=True
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Production", "Production"),
                            ("Development", "Development"),
                            ("Longhole", "Longhole"),
                            ("Logistics", "Logistics"),
                        ],
                        db_column="Section",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "coverageid",
                    models.ForeignKey(
                        blank=True,
                        db_column="CoverageID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.crewcoverage",
                    ),
                ),
                (
                    "crewid",
                    models.ForeignKey(
                        db_column="CrewID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.crews",
                    ),
                ),
                (
                    "ohapprovedby_capt",
                    models.ForeignKey(
                        blank=True,
                        db_column="OpsHApprovedBy_Capt",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="captain_headerapproved_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shifterid",
                    models.ForeignKey(
                        db_column="ShifterID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "OperationsHeader",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="OperationsEntry",
            fields=[
                (
                    "opsentryid",
                    models.AutoField(
                        db_column="OpsEntryID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "hoursworked",
                    models.DecimalField(
                        db_column="HoursWorked", decimal_places=2, max_digits=5
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, db_column="Remarks", null=True),
                ),
                (
                    "hauledto",
                    models.CharField(
                        blank=True, db_column="HauledTo", max_length=255, null=True
                    ),
                ),
                (
                    "tonnesorehauled",
                    models.DecimalField(
                        blank=True,
                        db_column="TonnesOreHauled",
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "tonneswastehauled",
                    models.DecimalField(
                        blank=True,
                        db_column="TonnesWasteHauled",
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "lowgradehauled",
                    models.DecimalField(
                        blank=True,
                        db_column="LowGradeHauled",
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "tonnesoreskipped",
                    models.DecimalField(
                        blank=True,
                        db_column="TonnesOreSkipped",
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "tonneswasteskipped",
                    models.DecimalField(
                        blank=True,
                        db_column="TonnesWasteSkipped",
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "lowgradeskipped",
                    models.DecimalField(
                        blank=True,
                        db_column="LowGradeSkipped",
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "longholefootage",
                    models.DecimalField(
                        blank=True,
                        db_column="LongHoleFootage",
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "linestatus",
                    models.CharField(
                        db_column="LineStatus", default="Draft", max_length=15
                    ),
                ),
                (
                    "paidat",
                    models.DateTimeField(blank=True, db_column="PaidAt", null=True),
                ),
                (
                    "approvedat_capt",
                    models.DateTimeField(
                        blank=True, db_column="ApprovedAt_Capt", null=True
                    ),
                ),
                (
                    "captainnote",
                    models.TextField(blank=True, db_column="CaptainNote", null=True),
                ),
                (
                    "accountid",
                    models.ForeignKey(
                        blank=True,
                        db_column="AccountID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.account",
                    ),
                ),
                (
                    "approvedby_capt",
                    models.ForeignKey(
                        blank=True,
                        db_column="ApprovedBy_Capt",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="captain_approved_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contractid",
                    models.ForeignKey(
                        db_column="ContractID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.contract",
                    ),
                ),
                (
                    "employeeid",
                    models.ForeignKey(
                        db_column="EmployeeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paidby",
                    models.ForeignKey(
                        blank=True,
                        db_column="PaidBy",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="paid_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workcategoryid",
                    models.ForeignKey(
                        blank=True,
                        db_column="WorkCategoryID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.workcategory",
                    ),
                ),
                (
                    "opsheaderid",
                    models.ForeignKey(
                        db_column="OpsHeaderID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.operationsheader",
                    ),
                ),
            ],
            options={
                "db_table": "OperationsEntry",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="OperationsBonus",
            fields=[
                (
                    "opsbonusid",
                    models.AutoField(
                        db_column="OpsBonusID", primary_key=True, serialize=False
                    ),
                ),
                ("bonusmonth", models.DateField(db_column="BonusMonth")),
                (
                    "bonusratecode",
                    models.CharField(
                        choices=[
                            ("1x", "1x"),
                            ("2x", "2x"),
                            ("3x", "3x"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                        ],
                        db_column="BonusRateCode",
                        max_length=2,
                    ),
                ),
                ("notes", models.TextField(blank=True, db_column="Notes", null=True)),
                (
                    "reviewedat",
                    models.DateTimeField(blank=True, db_column="ReviewedAt", null=True),
                ),
                (
                    "appliedatpayroll",
                    models.DateTimeField(
                        blank=True, db_column="AppliedAtPayroll", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Submitted", "Submitted"),
                            ("Applied", "Applied"),
                        ],
                        db_column="Status",
                        default="Draft",
                        max_length=10,
                    ),
                ),
                (
                    "appliedbypayroll",
                    models.ForeignKey(
                        blank=True,
                        db_column="AppliedByPayroll",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="applied_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employeeid",
                    models.ForeignKey(
                        db_column="EmployeeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewedby",
                    models.ForeignKey(
                        blank=True,
                        db_column="ReviewedBy",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reviewed_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "OperationsBonus",
                "managed": True,
                "unique_together": {("employeeid", "bonusmonth")},
            },
        ),
    ]
