# Generated by Django 5.2.14 on 2026-09-10 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "timesheets",
            "0029_auditlog_businessheader_businessentry_employeebonus_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="operationsentry",
            name="leavetypeid",
            field=models.ForeignKey(
                blank=True,
                db_column="LeaveTypeID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.leavetype",
            ),
        ),
        migrations.CreateModel(
            name="VacationRatePolicy",
            fields=[
                (
                    "policyid",
                    models.AutoField(
                        db_column="PolicyID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "bucket",
                    models.CharField(
                        choices=[
                            ("ops_development", "Operations - Development"),
                            ("ops_other", "Operations - Production/Longhole/Logistics"),
                            ("non_operations", "Non-Operations (Business/Maintenance)"),
                        ],
                        db_column="Bucket",
                        max_length=20,
                    ),
                ),
                ("effective_year", models.IntegerField(db_column="EffectiveYear")),
                (
                    "monthly_rate_hours",
                    models.DecimalField(
                        db_column="MonthlyRateHours", decimal_places=2, max_digits=4
                    ),
                ),
            ],
            options={
                "db_table": "VacationRatePolicy",
                "ordering": ["bucket", "-effective_year"],
                "managed": True,
                "unique_together": {("bucket", "effective_year")},
            },
        ),
        migrations.CreateModel(
            name="LieuDayLedger",
            fields=[
                (
                    "ledgerid",
                    models.AutoField(
                        db_column="LedgerID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Banked", "Banked"), ("Used", "Used")],
                        db_column="Status",
                        default="Banked",
                        max_length=10,
                    ),
                ),
                (
                    "earnedat",
                    models.DateTimeField(auto_now_add=True, db_column="EarnedAt"),
                ),
                (
                    "usedat",
                    models.DateTimeField(blank=True, db_column="UsedAt", null=True),
                ),
                (
                    "used_entry_type",
                    models.CharField(
                        blank=True, db_column="UsedEntryType", max_length=20, null=True
                    ),
                ),
                (
                    "used_entry_id",
                    models.IntegerField(blank=True, db_column="UsedEntryID", null=True),
                ),
                (
                    "employeeid",
                    models.ForeignKey(
                        db_column="EmployeeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "statholidayid",
                    models.ForeignKey(
                        db_column="StatHolidayID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="timesheets.statholiday",
                    ),
                ),
            ],
            options={
                "db_table": "LieuDayLedger",
                "managed": True,
                "unique_together": {("employeeid", "statholidayid")},
            },
        ),
    ]
