# Generated by Django 5.2.14 on 2026-09-11 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0030_operationsentry_leavetypeid_vacationratepolicy_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="businessheader",
            name="bh_approvedby_capt",
            field=models.ForeignKey(
                blank=True,
                db_column="BH_ApprovedBy_Capt",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="captain_headerapproved_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
