# Generated by Django 5.2.14 on 2026-09-11 17:20

import django.db.models.deletion
from django.db import migrations, models


def seed_and_migrate_ops_categories(apps, schema_editor):
    Workcategory = apps.get_model('timesheets', 'Workcategory')
    Opscategory = apps.get_model('timesheets', 'Opscategory')
    OperationsEntry = apps.get_model('timesheets', 'OperationsEntry')

    used_ids = OperationsEntry.objects.filter(
        workcategoryid_id__isnull=False
    ).values_list('workcategoryid_id', flat=True).distinct()

    for wc in Workcategory.objects.filter(categoryid__in=list(used_ids)):
        new_cat, _ = Opscategory.objects.get_or_create(
            categoryname=wc.categoryname,
            defaults={'isproductive': wc.isproductive, 'isactive': wc.isactive},
        )
        OperationsEntry.objects.filter(workcategoryid_id=wc.categoryid).update(opscategoryid_id=new_cat.pk)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0031_businessheader_bh_approvedby_capt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opscategory",
            fields=[
                (
                    "opscategoryid",
                    models.AutoField(
                        db_column="CategoryID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "categoryname",
                    models.CharField(db_column="CategoryName", max_length=255),
                ),
                ("isproductive", models.IntegerField(db_column="IsProductive")),
                ("isactive", models.IntegerField(db_column="IsActive", default=1)),
            ],
            options={
                "db_table": "OpsCategory",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="operationsentry",
            name="opscategoryid",
            field=models.ForeignKey(
                blank=True,
                db_column="OpsCategoryID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="timesheets.opscategory",
            ),
        ),
        migrations.RunPython(seed_and_migrate_ops_categories, noop_reverse),
        migrations.RemoveField(
            model_name="operationsentry",
            name="workcategoryid",
        ),
    ]
