# Generated by Django 5.2.14 on 2026-09-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "timesheets",
            "0032_opscategory_remove_operationsentry_workcategoryid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="businesscategory",
            name="ispayable",
            field=models.BooleanField(db_column="IsPayable", default=True),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="ispayable",
            field=models.BooleanField(db_column="IsPayable", default=True),
        ),
        migrations.AddField(
            model_name="opscategory",
            name="ispayable",
            field=models.BooleanField(db_column="IsPayable", default=True),
        ),
        migrations.AddField(
            model_name="workcategory",
            name="ispayable",
            field=models.BooleanField(db_column="IsPayable", default=True),
        ),
    ]
