# Generated by Django 5.2.14 on 2026-09-11 19:53

from django.db import migrations


def mark_unpaid_rows(apps, schema_editor):
    LeaveType = apps.get_model('timesheets', 'LeaveType')
    Workcategory = apps.get_model('timesheets', 'Workcategory')
    Businesscategory = apps.get_model('timesheets', 'Businesscategory')
    Opscategory = apps.get_model('timesheets', 'Opscategory')

    for Model in (LeaveType, Workcategory, Businesscategory, Opscategory):
        name_field = 'leavetypename' if Model is LeaveType else 'categoryname'
        for row in Model.objects.all():
            name = getattr(row, name_field).lower()
            if 'unpaid' in name or 'awol' in name:
                row.ispayable = False
                row.save(update_fields=['ispayable'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0033_businesscategory_ispayable_leavetype_ispayable_and_more"),
    ]

    operations = [
        migrations.RunPython(mark_unpaid_rows, noop_reverse),
    ]
