# Generated by Django 5.2.14 on 2026-09-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0034_seed_ispayable_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinerLevel",
            fields=[
                (
                    "levelid",
                    models.AutoField(
                        db_column="LevelID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "levelcode",
                    models.CharField(db_column="LevelCode", max_length=4, unique=True),
                ),
                ("sortorder", models.IntegerField(db_column="SortOrder", default=0)),
            ],
            options={
                "db_table": "MinerLevel",
                "ordering": ["sortorder", "levelcode"],
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="levels",
            field=models.ManyToManyField(
                blank=True,
                db_table="ContractLevelMap",
                related_name="contracts",
                to="timesheets.minerlevel",
            ),
        ),
    ]
