from django.urls import path 
from . import views

urlpatterns = [
    path('timesheet/new/', views.new_timesheet, name='new_timesheet'),
    path('timesheet/<int:pk>/', views.add_entry, name='add_entry'),
    path('timesheet/<int:pk>/delete/', views.delete_draft, name='delete_draft'),
    path('timesheet/drafts/', views.my_drafts, name='my_drafts'),
    path('timesheet/approved/', views.my_timesheets_approved, name='my_timesheets_approved'),
    path('timesheet/approved/<int:year>/<int:month>/', views.my_timesheets_approved_month, name='my_timesheets_approved_month'),
    path('timesheet/paid/', views.my_timesheets_paid, name='my_timesheets_paid'),
    path('timesheet/paid/<int:year>/<int:month>/', views.my_timesheets_paid_month, name='my_timesheets_paid_month'),
    path('supervisor/inbox/', views.approval_inbox, name='approval_inbox'),
    path('supervisor/review/<int:pk>/', views.review_timesheet, name='review_timesheet'),
    path('payroll/unprocessed/', views.payroll_unprocessed, name='payroll_unprocessed'),
    path('payroll/unprocessed/<int:dept_id>/', views.payroll_unprocessed_dept, name='payroll_unprocessed_dept'),
    path('payroll/unprocessed/<int:dept_id>/timesheet/<int:pk>/', views.payroll_unprocessed_review, name='payroll_unprocessed_review'),
    path('payroll/processed/', views.payroll_processed, name='payroll_processed'),
    path('payroll/processed/dept/<int:dept_id>/', views.payroll_processed_dept, name='payroll_processed_dept'),
    path('payroll/processed/employee/<str:employee_id>/', views.payroll_processed_employee, name='payroll_processed_employee'),
    path('payroll/ops/unprocessed/', views.payroll_ops_unprocessed, name='payroll_ops_unprocessed'),
    path('payroll/ops/unprocessed/<int:pk>/', views.payroll_ops_sheet, name='payroll_ops_sheet'),
    path('payroll/ops/processed/daily/', views.payroll_ops_daily, name='payroll_ops_daily'),
    path('payroll/ops/processed/daily/<int:year>/<int:month>/', views.payroll_ops_daily_month, name='payroll_ops_daily_month'),
    path('payroll/ops/processed/members/', views.payroll_ops_members, name='payroll_ops_members'),
    path('payroll/ops/processed/members/<str:employee_id>/', views.payroll_ops_member_detail, name='payroll_ops_member_detail'),
    path('payroll/ops/processed/members/<str:employee_id>/<int:year>/<int:month>/', views.payroll_ops_member_month, name='payroll_ops_member_month'),
    path('operations/new/', views.new_ops_sheet, name='new_ops_sheet'),
    path('operations/my-sheets/', views.my_ops_sheets, name='my_ops_sheets'),
    path('operations/my-sheets/approved/', views.my_ops_approvals, name='my_ops_approvals'),
    path('operations/my-sheets/approved/<int:year>/<int:month>/', views.my_ops_approvals_month, name='my_ops_approvals_month'),
    path('operations/captain/inbox/', views.ops_approval_inbox, name='ops_approval_inbox'),
    path('operations/captain/review/<int:pk>/', views.review_ops_sheet, name='review_ops_sheet'),
    path('operations/captain/completed/', views.my_ops_completed, name='my_ops_completed'),
    path('operations/captain/completed/<int:year>/<int:month>/', views.my_ops_completed_month, name='my_ops_completed_month'),
    path('operations/<int:pk>/', views.ops_sheet, name='ops_sheet'),
    path('operations/<int:pk>/delete/', views.delete_ops_draft, name='delete_ops_draft'),
    path('api/accounts/', views.accounts_for_contract, name='accounts_for_contract'),
    path('superintendent/contract-accounts/', views.contract_account_management, name='contract_account_management'),
    path('superintendent/ops/members/', views.superintendent_ops_members, name='superintendent_ops_members'),
    path('superintendent/ops/members/<str:employee_id>/', views.superintendent_ops_member_detail, name='superintendent_ops_member_detail'),
    path('superintendent/ops/members/<str:employee_id>/<int:year>/<int:month>/', views.superintendent_ops_member_month, name='superintendent_ops_member_month'),

]